# Generated by Django 4.0.5 on 2022-06-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recomendation',
            field=models.CharField(choices=[('Must Watch', 'Must Watch'), ('Should Watch', 'Should Watch'), ('Avoid Watch', 'Aoid Watch'), ('No Opinion', 'No Opinion')], default='No Opinion', max_length=30),
        ),
    ]
